on:
  push:
    branches:
    - master
    tags-ignore:
    - "*.*.*"

name: Build Json Schema

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Dependency
      uses: actions/setup-go@master
      with:
        go-version: "1.15"
    - name: Build Schema
      run: |
        go run main.go > ./concourse_jsonschema.json
    - name: Updat Schema
      uses: github-actions-x/commit@v2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Update json schema for Concourse by GitHub Action'
        force-add: 'true'
        files: ./concourse_jsonschema.json
        name: cappyzawa
        email: cappyzawa@yahoo.ne.jp
